//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDistribuidores_TiposFormulariosJANO
    {
        public int IdTipoFormularioJANO { get; set; }
        public string CodigoJANO { get; set; }
        public string Descripcion { get; set; }
    }
}
