//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDistribuidores_DatosAdicionalesTramitaciones
    {
        public int IdDatosAdicionalesTramitacion { get; set; }
        public int IdTramitacion { get; set; }
        public int IdTipoDato { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int IdEstadoTramitacion { get; set; }
        public int CantidadReintentos { get; set; }
        public string Error { get; set; }
    
        public virtual AppDistribuidores_TiposDatos AppDistribuidores_TiposDatos { get; set; }
    }
}
