//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDistribuidores_Tramitaciones
    {
        public int IdTramitacion { get; set; }
        public int IdPieza { get; set; }
        public int IdSistema { get; set; }
        public Nullable<long> NroEnvio { get; set; }
    }
}
