//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenRetiro
    {
        public int IdOrdenRetiro { get; set; }
        public int IdRemitente { get; set; }
        public int IdCliente { get; set; }
        public Nullable<bool> QuickShip { get; set; }
        public Nullable<int> NroOperativa { get; set; }
        public Nullable<int> CentroCosto { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public string NroCuentaTarjeta { get; set; }
        public string TitularPago { get; set; }
        public string VtoTarjeta { get; set; }
        public string DireccionTitular { get; set; }
        public string CodPostalTitularPago { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<int> IdFranjaHoraria { get; set; }
        public Nullable<int> EstadoOrden { get; set; }
        public Nullable<System.DateTime> FechaEstado { get; set; }
        public Nullable<int> ImposicionSucursal { get; set; }
        public Nullable<bool> RecibirDetalle { get; set; }
        public Nullable<bool> EnviarDetalle { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public int IdSucursalOCA { get; set; }
        public string DomicilioRetiro { get; set; }
        public string NumeroRetiro { get; set; }
        public string PisoRetiro { get; set; }
        public string DeptoRetiro { get; set; }
        public Nullable<int> IdCodPostalRetiro { get; set; }
        public string LocalidadRetiro { get; set; }
        public string PciaRetiro { get; set; }
        public string ContactoRetiro { get; set; }
        public string Solicitante { get; set; }
        public string NroImposicion { get; set; }
        public Nullable<int> NroRecorrido { get; set; }
        public string OrigenCarga { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CantidadPaquetes { get; set; }
        public Nullable<int> CantidadRecibida { get; set; }
        public Nullable<int> IdUsuarioWEB { get; set; }
        public string TelefonoRetiro { get; set; }
        public Nullable<byte> IdTipoEntregaFact { get; set; }
        public Nullable<bool> GeneroBonifija { get; set; }
        public byte CargaParcial { get; set; }
        public string eCorreoRetiro { get; set; }
    }
}
