//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TH_OCA_DESAEntities : DbContext
    {
        public TH_OCA_DESAEntities()
            : base("name=TH_OCA_DESAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<THUBAN_INDEXES_DISTRIBUCION> THUBAN_INDEXES_DISTRIBUCION { get; set; }
        public virtual DbSet<THUBAN_STORE> THUBAN_STORE { get; set; }
    }
}
