//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUBAN_STORE
    {
        public string STORE_ITEM_ID { get; set; }
        public string STORE_ITEM_CLASS { get; set; }
        public string STORE_ITEM_NAME { get; set; }
        public string STORE_FILE_PATH { get; set; }
        public string STORE_CONNECTOR { get; set; }
        public string STORE_CONNECTOR_ID { get; set; }
        public string STORE_FILE_SIZE { get; set; }
        public Nullable<int> STORE_FILE_PAGES { get; set; }
        public string STORE_FILE_TYPE { get; set; }
        public Nullable<int> STORE_STATUS { get; set; }
        public string STORE_OWNER { get; set; }
        public string STORE_CREATION_DATE { get; set; }
        public string STORE_MODIF_DATE { get; set; }
        public string STORE_VERSION { get; set; }
        public string STORE_FULLTEXT_INDEX { get; set; }
    }
}
