//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUBAN_INDEXES_DISTRIBUCION
    {
        public string INDEX_ITEM_ID { get; set; }
        public string INDEX_ITEM_CLASS { get; set; }
        public string INDEX_ITEM_NAME { get; set; }
        public string TIPO_FOTO { get; set; }
        public string N_GUIA { get; set; }
        public string ID_PIEZA { get; set; }
        public string N_CUENTA { get; set; }
        public string D_OPERATIVA { get; set; }
        public Nullable<System.DateTime> FECHA_VISITA { get; set; }
        public string DNI { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public string SUC_TRAMITACION { get; set; }
        public Nullable<int> D_MOTIVO { get; set; }
        public string USER_DISTRIB { get; set; }
    }
}
